In [1]:
import os
import numpy as np
import pandas as pd
import pyedflib
from pyedflib import highlevel
from scipy.signal import resample
from sklearn.utils import shuffle
import json
import warnings
from collections import defaultdict
warnings.filterwarnings("ignore")

In [2]:
import mne
from mne.preprocessing import ICA
try:
    from mne_icalabel import label_components
except Exception:
    label_components = None

In [3]:
# multi-scale sampling rates
SAMPLE_RATE_LIST = [200, 100, 50]  # Hz

# fixed segment length in samples (timestamps)
SEG_LEN = 400  # number of time steps per segment
# overlap in samples (timestamps), not in seconds
OVERLAP = 200    # e.g. 200 means 50% overlap for SEG_LEN=400

assert 0 <= OVERLAP < SEG_LEN, "OVERLAP must be in [0, SEG_LEN)."

sub_folder_path = f"L{SEG_LEN}"
sub_folder_path

'L400'

In [4]:
root = 'CAUEEG/'
# participants file path
annotation_path = os.path.join(root, 'annotation.xlsx')
annotations = pd.read_excel(annotation_path)
annotations

,serial,age,dementia,ad,load,eoad,vd,sivd,ad_vd_mixed,mci,...,ftd,bvftd,language_ftd,semantic_aphasia,non_fluent_aphasia,parkinson_synd,parkinson_disease,parkinson_dementia,nph,tga
0,1,78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,78,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1374,1384,57,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1375,1385,77,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1376,1386,80,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1377,1387,83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1378,1388,73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Labels

In [5]:
conditions = [
    annotations["dementia"] == 1,         # condition 1：Dementia: Alzheimer's Disease, Vascular Dementia, Parkinson's Dementia 
    annotations["mci"] == 1,        # condition 2：Mild Cognitive Impairment
    annotations["normal"] == 1      # condition 3：Normal control
]
choices = [1, 2, 0]        # corresponding labels, De=1, MCI=2, NC=0

# np.select, if no condition is met, default to 3
annotations["label"] = np.select(conditions, choices, default=3)
annotations

,serial,age,dementia,ad,load,eoad,vd,sivd,ad_vd_mixed,mci,...,bvftd,language_ftd,semantic_aphasia,non_fluent_aphasia,parkinson_synd,parkinson_disease,parkinson_dementia,nph,tga,label
0,1,78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
1,2,56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,3,93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
3,4,78,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,5,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1374,1384,57,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1375,1385,77,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1376,1386,80,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1377,1387,83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
1378,1388,73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2

## Features

In [6]:
f = pyedflib.EdfReader("CAUEEG/signal/edf/00001.edf")
channels = f.getSignalLabels()
f.close()

In [7]:
channels

['Fp1-AVG',
 'F3-AVG',
 'C3-AVG',
 'P3-AVG',
 'O1-AVG',
 'Fp2-AVG',
 'F4-AVG',
 'C4-AVG',
 'P4-AVG',
 'O2-AVG',
 'F7-AVG',
 'T3-AVG',
 'T5-AVG',
 'F8-AVG',
 'T4-AVG',
 'T6-AVG',
 'FZ-AVG',
 'CZ-AVG',
 'PZ-AVG',
 'EKG',
 'Photic']

In [8]:
# 'Fp1', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'T3', 'C3', 'Cz', 'C4', 'T4', 'T5', 'P3', 'Pz', 'P4', 'T6', 'O1', 'O2'
li_std_ch = ['Fp1-AVG', 'Fp2-AVG', 'F7-AVG', 'F3-AVG', 'FZ-AVG', 'F4-AVG', 'F8-AVG', 'T3-AVG', 'C3-AVG', 'CZ-AVG', 'C4-AVG', 'T4-AVG', 'T5-AVG', 'P3-AVG', 'PZ-AVG', 'P4-AVG', 'T6-AVG', 'O1-AVG', 'O2-AVG']

In [9]:
def generate_mask_from_events(json_path, total_samples, sample_rate=256, artifact_keywords=None):
    """
    Generate a boolean mask for valid EEG samples based on events.
    Marks valid recording periods and excludes artifacts + HV intervals.

    Parameters
    ----------
    json_path : str
        Path to the event JSON file.
    total_samples : int
        Total number of EEG samples.
    sample_rate : int
        Sampling rate in Hz (default: 256).
    artifact_keywords : list of str, optional
        Keywords to detect noisy artifacts (default: common EEG noise terms).

    Returns
    -------
    mask : np.ndarray of bool
        Boolean array indicating valid EEG data samples.
    """

    if artifact_keywords is None:
        artifact_keywords = [
            'artifact', 'blink', 'eye', 'noise', 'movement', 'move', 'cough',
            'muscle', 'chewing', 'swallow', 'talk', 'sleep', 'sweating', 'jerking', 'drowsy'
        ]

    with open(json_path, 'r') as f:
        events = json.load(f)

    mask = np.zeros(total_samples, dtype=bool)

    # Step 1: Mark valid recording periods
    is_recording = False
    segment_start = None
    for timestamp, label in events:
        label_lower = label.lower()
        if label_lower in ("start recording", "recording resumed"):
            segment_start = timestamp
            is_recording = True
        elif label_lower == "paused" and is_recording:
            segment_end = timestamp
            mask[segment_start:min(segment_end, total_samples)] = True
            is_recording = False
            segment_start = None

    # Step 2: Remove artifact regions (±1s)
    for timestamp, label in events:
        label_lower = label.lower()
        if any(key in label_lower for key in artifact_keywords):
            start = max(0, timestamp - int(1 * sample_rate))
            end = min(total_samples, timestamp + int(1 * sample_rate))
            mask[start:end] = False

    return mask

In [10]:
def data_preprocessing(
    eeg_data: np.ndarray,
    sfreq: float,
    ch_names: list,
    resample_sfreq: float = 200.0,
    verbose=True
):
    """
    Clean EEG data using bandpass filtering, percentile-based bad channel detection,
    ICA + ICLabel artifact removal, resampling, re-referencing, epoching, and z-score normalization.

    Args:
        eeg_data (np.ndarray): EEG data, shape (T, C).
        sfreq (float): Original sampling frequency.
        ch_names (list): List of channel names.
        resample_sfreq (float): Target sampling frequency.
        verbose (bool): Verbose output.

    Returns:
        np.ndarray: Cleaned, normalized EEG data, shape (n_epochs, time_steps, channels).
    """
    # 1. Construct MNE Raw object
    info = mne.create_info(ch_names=ch_names, sfreq=sfreq, ch_types=['eeg'] * len(ch_names))
    raw = mne.io.RawArray(eeg_data.T, info)

    # 2. Set Montage
    raw.set_montage(mne.channels.make_standard_montage('standard_1020'))
    if verbose:
        print("✔ Montage set: 'standard_1020'.")

    #  Bandpass Filter (0.5–45 Hz)
    raw.filter(l_freq=0.5, h_freq=45.0, verbose=False)
    if verbose:
        print("✔ Bandpass filter applied (0.5–45 Hz).")
        
    return raw.get_data().T, raw.n_times
        

def eeg_data(std_edf_path, event_path, li_std_ch, target_freq=128):
    signals, signal_headers, _ = highlevel.read_edf(std_edf_path, ch_names=li_std_ch)
    freq = signal_headers[0]['sample_frequency']
    print("Original frequency ", freq)
    data = signals.T
    print("Raw data shape ", data.shape)
    mask = generate_mask_from_events(event_path, data.shape[0], freq)
    data = data[mask]
    print("Cleaned data shape ", data.shape)
    return data

In [11]:
def resample_time_series(data, original_fs, target_fs):
    """
    Resample each channel independently.
    data: (T_raw, C)
    return: (T_new, C)
    """
    T, C = data.shape
    new_length = int(T * target_fs / original_fs)
    resampled_data = np.zeros((new_length, C), dtype=np.float32)
    for i in range(C):
        # resample one channel
        resampled_data[:, i] = resample(data[:, i], new_length)
    return resampled_data


def compute_step(seg_len, overlap):
    """
    Compute sliding step (in samples) given segment length and overlap.
    """
    step = seg_len - overlap
    if step <= 0:
        raise ValueError(f"Invalid overlap={overlap}: step <= 0.")
    return step


def compute_num_segments(num_samples, seg_len, step):
    """
    Compute how many segments can be extracted from a sequence
    with given segment length and step.
    """
    if num_samples < seg_len:
        return 0
    return 1 + (num_samples - seg_len) // step

## PASS 1: Find total number of segments across all subjects

In [12]:
subject_segment_counts = defaultdict(lambda: defaultdict(int))
N_total = 0
n_channels = len(li_std_ch)

# step (timestamps)
STEP = compute_step(SEG_LEN, OVERLAP)
print("SEG_LEN =", SEG_LEN, "OVERLAP =", OVERLAP, "STEP =", STEP)

file_root_path = 'CAUEEG/signal/edf/'
event_root_path = 'CAUEEG/event/'
for file, event in zip(os.listdir(file_root_path), os.listdir(event_root_path)):
    if file.endswith('.edf'):
        # file example: '00001.edf'
        sub = file[:-4]  # subject ID
        print(f"[PASS 1] Subject: {file}")
        file_path = os.path.join(file_root_path, file)
        event_path = os.path.join(event_root_path, event)
        for fs in SAMPLE_RATE_LIST:
            data = eeg_data(file_path, event_path, li_std_ch, fs)
            T_raw = data.shape[0]
            print("  Original length T_raw =", T_raw)
            # resampled length if each trial
            original_fs = 200.0  # original sampling rate
            T_res = int(T_raw * fs / original_fs)
            # compute number of segments
            n_seg = compute_num_segments(T_res, SEG_LEN, STEP)
            subject_segment_counts[sub][fs] += n_seg
            N_total += n_seg
            print(f"fs={fs}Hz: T_res={T_res}, STEP={STEP}, n_seg={n_seg}")
            print("----------------------------------------")
        print("----------------End of Subject-----------------\n")

print("\n===================================")
print("Total segments N_total =", N_total)
print("Channels =", n_channels)
print("===================================")

if N_total == 0:
    raise RuntimeError("No segments found. Please check SEG_LEN / OVERLAP.")

SEG_LEN = 400 OVERLAP = 200 STEP = 200
[PASS 1] Subject: 00001.edf
Original frequency  200.0
Raw data shape  (145600, 19)
Cleaned data shape  (133400, 19)
  Original length T_raw = 133400
fs=200Hz: T_res=133400, STEP=200, n_seg=666
----------------------------------------
Original frequency  200.0
Raw data shape  (145600, 19)
Cleaned data shape  (133400, 19)
  Original length T_raw = 133400
fs=100Hz: T_res=66700, STEP=200, n_seg=332
----------------------------------------
Original frequency  200.0
Raw data shape  (145600, 19)
Cleaned data shape  (133400, 19)
  Original length T_raw = 133400
fs=50Hz: T_res=33350, STEP=200, n_seg=165
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00002.edf
Original frequency  200.0
Raw data shape  (208600, 19)
Cleaned data shape  (191944, 19)
  Original length T_raw = 191944
fs=200Hz: T_res=191944, STEP=200, n_seg=958
----------------------------------------
Original frequency  200.0
Raw data shape  (208600, 19)
Cleaned data shape  (191944, 19)
  Original length T_raw = 191944
fs=100Hz: T_res=95972, STEP=200, n_seg=478
----------------------------------------
Original frequency  200.0
Raw data shape  (208600, 19)
Cleaned data shape  (191944, 19)
  Original length T_raw = 191944
fs=50Hz: T_res=47986, STEP=200, n_seg=238
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00003.edf
Original frequency  200.0
Raw data shape  (130200, 19)
Cleaned data shape  (123600, 19)
  Original length T_raw = 123600
fs=200Hz: T_res=123600, STEP=200, n_seg=617
----------------------------------------
Original frequency  200.0
Raw data shape  (130200, 19)
Cleaned data shape  (123600, 19)
  Original length T_raw = 123600
fs=100Hz: T_res=61800, STEP=200, n_seg=308
----------------------------------------
Original frequency  200.0
Raw data shape  (130200, 19)
Cleaned data shape  (123600, 19)
  Original length T_raw = 123600
fs=50Hz: T_res=30900, STEP=200, n_seg=153
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00004.edf
Original frequency  200.0
Raw data shape  (169400, 19)
Cleaned data shape  (152600, 19)
  Original length T_raw = 152600
fs=200Hz: T_res=152600, STEP=200, n_seg=762
----------------------------------------
Original frequency  200.0
Raw data shape  (169400, 19)
Cleaned data shape  (152600, 19)
  Original length T_raw = 152600
fs=100Hz: T_res=76300, STEP=200, n_seg=380
----------------------------------------
Original frequency  200.0
Raw data shape  (169400, 19)
Cleaned data shape  (152600, 19)
  Original length T_raw = 152600
fs=50Hz: T_res=38150, STEP=200, n_seg=189
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00005.edf
Original frequency  200.0
Raw data shape  (183400, 19)
Cleaned data shape  (159126, 19)
  Original length T_raw = 159126
fs=200Hz: T_res=159126, STEP=200, n_seg=794
----------------------------------------
Original frequency  200.0
Raw data shape  (183400, 19)
Cleaned data shape  (159126, 19)
  Original length T_raw = 159126
fs=100Hz: T_res=79563, STEP=200, n_seg=396
----------------------------------------
Original frequency  200.0
Raw data shape  (183400, 19)
Cleaned data shape  (159126, 19)
  Original length T_raw = 159126
fs=50Hz: T_res=39781, STEP=200, n_seg=197
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00006.edf
Original frequency  200.0
Raw data shape  (168000, 19)
Cleaned data shape  (150200, 19)
  Original length T_raw = 150200
fs=200Hz: T_res=150200, STEP=200, n_seg=750
----------------------------------------
Original frequency  200.0
Raw data shape  (168000, 19)
Cleaned data shape  (150200, 19)
  Original length T_raw = 150200
fs=100Hz: T_res=75100, STEP=200, n_seg=374
----------------------------------------
Original frequency  200.0
Raw data shape  (168000, 19)
Cleaned data shape  (150200, 19)
  Original length T_raw = 150200
fs=50Hz: T_res=37550, STEP=200, n_seg=186
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00007.edf
Original frequency  200.0
Raw data shape  (180600, 19)
Cleaned data shape  (164400, 19)
  Original length T_raw = 164400
fs=200Hz: T_res=164400, STEP=200, n_seg=821
----------------------------------------
Original frequency  200.0
Raw data shape  (180600, 19)
Cleaned data shape  (164400, 19)
  Original length T_raw = 164400
fs=100Hz: T_res=82200, STEP=200, n_seg=410
----------------------------------------
Original frequency  200.0
Raw data shape  (180600, 19)
Cleaned data shape  (164400, 19)
  Original length T_raw = 164400
fs=50Hz: T_res=41100, STEP=200, n_seg=204
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00008.edf
Original frequency  200.0
Raw data shape  (100800, 19)
Cleaned data shape  (90030, 19)
  Original length T_raw = 90030
fs=200Hz: T_res=90030, STEP=200, n_seg=449
----------------------------------------
Original frequency  200.0
Raw data shape  (100800, 19)
Cleaned data shape  (90030, 19)
  Original length T_raw = 90030
fs=100Hz: T_res=45015, STEP=200, n_seg=224
----------------------------------------
Original frequency  200.0
Raw data shape  (100800, 19)
Cleaned data shape  (90030, 19)
  Original length T_raw = 90030
fs=50Hz: T_res=22507, STEP=200, n_seg=111
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00010.edf
Original frequency  200.0
Raw data shape  (201600, 19)
Cleaned data shape  (193600, 19)
  Original length T_raw = 193600
fs=200Hz: T_res=193600, STEP=200, n_seg=967
----------------------------------------
Original frequency  200.0
Raw data shape  (201600, 19)
Cleaned data shape  (193600, 19)
  Original length T_raw = 193600
fs=100Hz: T_res=96800, STEP=200, n_seg=483
----------------------------------------
Original frequency  200.0
Raw data shape  (201600, 19)
Cleaned data shape  (193600, 19)
  Original length T_raw = 193600
fs=50Hz: T_res=48400, STEP=200, n_seg=241
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00011.edf
Original frequency  200.0
Raw data shape  (183400, 19)
Cleaned data shape  (166800, 19)
  Original length T_raw = 166800
fs=200Hz: T_res=166800, STEP=200, n_seg=833
----------------------------------------
Original frequency  200.0
Raw data shape  (183400, 19)
Cleaned data shape  (166800, 19)
  Original length T_raw = 166800
fs=100Hz: T_res=83400, STEP=200, n_seg=416
----------------------------------------
Original frequency  200.0
Raw data shape  (183400, 19)
Cleaned data shape  (166800, 19)
  Original length T_raw = 166800
fs=50Hz: T_res=41700, STEP=200, n_seg=207
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00012.edf
Original frequency  200.0
Raw data shape  (152600, 19)
Cleaned data shape  (136400, 19)
  Original length T_raw = 136400
fs=200Hz: T_res=136400, STEP=200, n_seg=681
----------------------------------------
Original frequency  200.0
Raw data shape  (152600, 19)
Cleaned data shape  (136400, 19)
  Original length T_raw = 136400
fs=100Hz: T_res=68200, STEP=200, n_seg=340
----------------------------------------
Original frequency  200.0
Raw data shape  (152600, 19)
Cleaned data shape  (136400, 19)
  Original length T_raw = 136400
fs=50Hz: T_res=34100, STEP=200, n_seg=169
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00013.edf
Original frequency  200.0
Raw data shape  (163800, 19)
Cleaned data shape  (137214, 19)
  Original length T_raw = 137214
fs=200Hz: T_res=137214, STEP=200, n_seg=685
----------------------------------------
Original frequency  200.0
Raw data shape  (163800, 19)
Cleaned data shape  (137214, 19)
  Original length T_raw = 137214
fs=100Hz: T_res=68607, STEP=200, n_seg=342
----------------------------------------
Original frequency  200.0
Raw data shape  (163800, 19)
Cleaned data shape  (137214, 19)
  Original length T_raw = 137214
fs=50Hz: T_res=34303, STEP=200, n_seg=170
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00014.edf
Original frequency  200.0
Raw data shape  (128800, 19)
Cleaned data shape  (121600, 19)
  Original length T_raw = 121600
fs=200Hz: T_res=121600, STEP=200, n_seg=607
----------------------------------------
Original frequency  200.0
Raw data shape  (128800, 19)
Cleaned data shape  (121600, 19)
  Original length T_raw = 121600
fs=100Hz: T_res=60800, STEP=200, n_seg=303
----------------------------------------
Original frequency  200.0
Raw data shape  (128800, 19)
Cleaned data shape  (121600, 19)
  Original length T_raw = 121600
fs=50Hz: T_res=30400, STEP=200, n_seg=151
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00015.edf
Original frequency  200.0
Raw data shape  (176400, 19)
Cleaned data shape  (163400, 19)
  Original length T_raw = 163400
fs=200Hz: T_res=163400, STEP=200, n_seg=816
----------------------------------------
Original frequency  200.0
Raw data shape  (176400, 19)
Cleaned data shape  (163400, 19)
  Original length T_raw = 163400
fs=100Hz: T_res=81700, STEP=200, n_seg=407
----------------------------------------
Original frequency  200.0
Raw data shape  (176400, 19)
Cleaned data shape  (163400, 19)
  Original length T_raw = 163400
fs=50Hz: T_res=40850, STEP=200, n_seg=203
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00016.edf
Original frequency  200.0
Raw data shape  (124600, 19)
Cleaned data shape  (116000, 19)
  Original length T_raw = 116000
fs=200Hz: T_res=116000, STEP=200, n_seg=579
----------------------------------------
Original frequency  200.0
Raw data shape  (124600, 19)
Cleaned data shape  (116000, 19)
  Original length T_raw = 116000
fs=100Hz: T_res=58000, STEP=200, n_seg=289
----------------------------------------
Original frequency  200.0
Raw data shape  (124600, 19)
Cleaned data shape  (116000, 19)
  Original length T_raw = 116000
fs=50Hz: T_res=29000, STEP=200, n_seg=144
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00017.edf
Original frequency  200.0
Raw data shape  (121800, 19)
Cleaned data shape  (108600, 19)
  Original length T_raw = 108600
fs=200Hz: T_res=108600, STEP=200, n_seg=542
----------------------------------------
Original frequency  200.0
Raw data shape  (121800, 19)
Cleaned data shape  (108600, 19)
  Original length T_raw = 108600
fs=100Hz: T_res=54300, STEP=200, n_seg=270
----------------------------------------
Original frequency  200.0
Raw data shape  (121800, 19)
Cleaned data shape  (108600, 19)
  Original length T_raw = 108600
fs=50Hz: T_res=27150, STEP=200, n_seg=134
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00018.edf
Original frequency  200.0
Raw data shape  (176400, 19)
Cleaned data shape  (165400, 19)
  Original length T_raw = 165400
fs=200Hz: T_res=165400, STEP=200, n_seg=826
----------------------------------------
Original frequency  200.0
Raw data shape  (176400, 19)
Cleaned data shape  (165400, 19)
  Original length T_raw = 165400
fs=100Hz: T_res=82700, STEP=200, n_seg=412
----------------------------------------
Original frequency  200.0
Raw data shape  (176400, 19)
Cleaned data shape  (165400, 19)
  Original length T_raw = 165400
fs=50Hz: T_res=41350, STEP=200, n_seg=205
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00019.edf
Original frequency  200.0
Raw data shape  (121800, 19)
Cleaned data shape  (108400, 19)
  Original length T_raw = 108400
fs=200Hz: T_res=108400, STEP=200, n_seg=541
----------------------------------------
Original frequency  200.0
Raw data shape  (121800, 19)
Cleaned data shape  (108400, 19)
  Original length T_raw = 108400
fs=100Hz: T_res=54200, STEP=200, n_seg=270
----------------------------------------
Original frequency  200.0
Raw data shape  (121800, 19)
Cleaned data shape  (108400, 19)
  Original length T_raw = 108400
fs=50Hz: T_res=27100, STEP=200, n_seg=134
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00020.edf
Original frequency  200.0
Raw data shape  (152600, 19)
Cleaned data shape  (147200, 19)
  Original length T_raw = 147200
fs=200Hz: T_res=147200, STEP=200, n_seg=735
----------------------------------------
Original frequency  200.0
Raw data shape  (152600, 19)
Cleaned data shape  (147200, 19)
  Original length T_raw = 147200
fs=100Hz: T_res=73600, STEP=200, n_seg=367
----------------------------------------
Original frequency  200.0
Raw data shape  (152600, 19)
Cleaned data shape  (147200, 19)
  Original length T_raw = 147200
fs=50Hz: T_res=36800, STEP=200, n_seg=183
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00021.edf
Original frequency  200.0
Raw data shape  (180600, 19)
Cleaned data shape  (168400, 19)
  Original length T_raw = 168400
fs=200Hz: T_res=168400, STEP=200, n_seg=841
----------------------------------------
Original frequency  200.0
Raw data shape  (180600, 19)
Cleaned data shape  (168400, 19)
  Original length T_raw = 168400
fs=100Hz: T_res=84200, STEP=200, n_seg=420
----------------------------------------
Original frequency  200.0
Raw data shape  (180600, 19)
Cleaned data shape  (168400, 19)
  Original length T_raw = 168400
fs=50Hz: T_res=42100, STEP=200, n_seg=209
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00022.edf
Original frequency  200.0
Raw data shape  (120400, 19)
Cleaned data shape  (112000, 19)
  Original length T_raw = 112000
fs=200Hz: T_res=112000, STEP=200, n_seg=559
----------------------------------------
Original frequency  200.0
Raw data shape  (120400, 19)
Cleaned data shape  (112000, 19)
  Original length T_raw = 112000
fs=100Hz: T_res=56000, STEP=200, n_seg=279
----------------------------------------
Original frequency  200.0
Raw data shape  (120400, 19)
Cleaned data shape  (112000, 19)
  Original length T_raw = 112000
fs=50Hz: T_res=28000, STEP=200, n_seg=139
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00023.edf
Original frequency  200.0
Raw data shape  (194600, 19)
Cleaned data shape  (182010, 19)
  Original length T_raw = 182010
fs=200Hz: T_res=182010, STEP=200, n_seg=909
----------------------------------------
Original frequency  200.0
Raw data shape  (194600, 19)
Cleaned data shape  (182010, 19)
  Original length T_raw = 182010
fs=100Hz: T_res=91005, STEP=200, n_seg=454
----------------------------------------
Original frequency  200.0
Raw data shape  (194600, 19)
Cleaned data shape  (182010, 19)
  Original length T_raw = 182010
fs=50Hz: T_res=45502, STEP=200, n_seg=226
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00024.edf
Original frequency  200.0
Raw data shape  (247800, 19)
Cleaned data shape  (237800, 19)
  Original length T_raw = 237800
fs=200Hz: T_res=237800, STEP=200, n_seg=1188
----------------------------------------
Original frequency  200.0
Raw data shape  (247800, 19)
Cleaned data shape  (237800, 19)
  Original length T_raw = 237800
fs=100Hz: T_res=118900, STEP=200, n_seg=593
----------------------------------------
Original frequency  200.0
Raw data shape  (247800, 19)
Cleaned data shape  (237800, 19)
  Original length T_raw = 237800
fs=50Hz: T_res=59450, STEP=200, n_seg=296
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00025.edf
Original frequency  200.0
Raw data shape  (120400, 19)
Cleaned data shape  (114000, 19)
  Original length T_raw = 114000
fs=200Hz: T_res=114000, STEP=200, n_seg=569
----------------------------------------
Original frequency  200.0
Raw data shape  (120400, 19)
Cleaned data shape  (114000, 19)
  Original length T_raw = 114000
fs=100Hz: T_res=57000, STEP=200, n_seg=284
----------------------------------------
Original frequency  200.0
Raw data shape  (120400, 19)
Cleaned data shape  (114000, 19)
  Original length T_raw = 114000
fs=50Hz: T_res=28500, STEP=200, n_seg=141
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00026.edf
Original frequency  200.0
Raw data shape  (184800, 19)
Cleaned data shape  (174854, 19)
  Original length T_raw = 174854
fs=200Hz: T_res=174854, STEP=200, n_seg=873
----------------------------------------
Original frequency  200.0
Raw data shape  (184800, 19)
Cleaned data shape  (174854, 19)
  Original length T_raw = 174854
fs=100Hz: T_res=87427, STEP=200, n_seg=436
----------------------------------------
Original frequency  200.0
Raw data shape  (184800, 19)
Cleaned data shape  (174854, 19)
  Original length T_raw = 174854
fs=50Hz: T_res=43713, STEP=200, n_seg=217
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00027.edf
Original frequency  200.0
Raw data shape  (180600, 19)
Cleaned data shape  (171600, 19)
  Original length T_raw = 171600
fs=200Hz: T_res=171600, STEP=200, n_seg=857
----------------------------------------
Original frequency  200.0
Raw data shape  (180600, 19)
Cleaned data shape  (171600, 19)
  Original length T_raw = 171600
fs=100Hz: T_res=85800, STEP=200, n_seg=428
----------------------------------------
Original frequency  200.0
Raw data shape  (180600, 19)
Cleaned data shape  (171600, 19)
  Original length T_raw = 171600
fs=50Hz: T_res=42900, STEP=200, n_seg=213
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00028.edf
Original frequency  200.0
Raw data shape  (204400, 19)
Cleaned data shape  (186000, 19)
  Original length T_raw = 186000
fs=200Hz: T_res=186000, STEP=200, n_seg=929
----------------------------------------
Original frequency  200.0
Raw data shape  (204400, 19)
Cleaned data shape  (186000, 19)
  Original length T_raw = 186000
fs=100Hz: T_res=93000, STEP=200, n_seg=464
----------------------------------------
Original frequency  200.0
Raw data shape  (204400, 19)
Cleaned data shape  (186000, 19)
  Original length T_raw = 186000
fs=50Hz: T_res=46500, STEP=200, n_seg=231
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00029.edf
Original frequency  200.0
Raw data shape  (169400, 19)
Cleaned data shape  (158600, 19)
  Original length T_raw = 158600
fs=200Hz: T_res=158600, STEP=200, n_seg=792
----------------------------------------
Original frequency  200.0
Raw data shape  (169400, 19)
Cleaned data shape  (158600, 19)
  Original length T_raw = 158600
fs=100Hz: T_res=79300, STEP=200, n_seg=395
----------------------------------------
Original frequency  200.0
Raw data shape  (169400, 19)
Cleaned data shape  (158600, 19)
  Original length T_raw = 158600
fs=50Hz: T_res=39650, STEP=200, n_seg=197
----------------------------------------
----------------End of Subject-----------------

[PASS 1] Subject: 00030.edf
Original frequency  200.0
Raw data shape  (183400, 19)
Cleaned data shape  (170400, 19)
  Original length T_raw = 170400
fs=200Hz: T_res=170400, STEP=200, n_seg=851
----------------------------------------
Original frequency  200.0
Raw data shape  (183400, 19)
Cleaned data shape  (170400, 19)
  Original length T_raw = 170400
fs=100Hz: T_res=85200, STEP=200, n_seg=425
----------------------------------------
Original frequency  200.0
Raw data shape  (183400, 19)
Cleaned data shape  (170400, 19)
  Original length T_raw = 170400

In [16]:
output_root = os.path.join('Processed', sub_folder_path, 'CAUEEG')
os.makedirs(output_root, exist_ok=True)

X_path = os.path.join(output_root, 'X.dat')
y_path = os.path.join(output_root, 'y.dat')
meta_path = os.path.join(output_root, 'meta.json')

print("X path:", X_path)
print("y path:", y_path)

# create memmap storage
X_mm = np.memmap(X_path, dtype='float32', mode='w+', shape=(N_total, SEG_LEN, n_channels))
y_mm = np.memmap(y_path, dtype='float32', mode='w+', shape=(N_total, 3))

X path: Processed\L400\CAUEEG\X.dat
y path: Processed\L400\CAUEEG\y.dat

## PASS 2: Process and store segments into memmap

In [17]:
cur = 0  # current index in memmap
total_seconds_all = 0  # used for total hours calculation
for file, event in zip(os.listdir(file_root_path), os.listdir(event_root_path)):
    if file.endswith('.edf'):
        # file example: '00001.edf'
        sub = file[:-4]  # subject ID
        file_path = os.path.join(file_root_path, file)
        event_path = os.path.join(event_root_path, event)
        pid = int(sub)
        label = annotations.loc[annotations['serial'] == pid]['label'].values[0]
    
        total_seg_sub = sum(subject_segment_counts[sub][fs] for fs in SAMPLE_RATE_LIST)
        if total_seg_sub == 0:
            continue
        print(f"[PASS 2] Subject: {sub}, expected total segments={total_seg_sub}")
    
        # load full data
        original_fs = 200.0  # original sampling rate
        data_raw = eeg_data(file_path, event_path, li_std_ch, original_fs).astype('float32')  # (T, C)
        total_seconds_all += data_raw.shape[0] / original_fs
        print("raw shape:", data_raw.shape)

        for fs in SAMPLE_RATE_LIST:
            # resample to target fs
            data = resample_time_series(data_raw, original_fs, fs)
            T_res, _ = data.shape
            print(f"fs={fs}Hz: resampled shape={data.shape}")

            # overlapped sliding window with fixed STEP (in timestamps)
            starts = np.arange(0, T_res - SEG_LEN + 1, STEP, dtype=int)
            print(f"fs={fs}Hz: segments={len(starts)}")

            for s in starts:
                if cur >= N_total:
                    raise RuntimeError("Exceeded predicted N_total.")

                X_mm[cur] = data[s:s + SEG_LEN]   # (SEG_LEN, C)
                y_mm[cur, 0] = float(label)       # label
                y_mm[cur, 1] = float(pid)         # subject ID
                y_mm[cur, 2] = float(fs)          # sample rate (scale)
                cur += 1
    print("-------------------------------------\n")

total_hours_all = total_seconds_all / 3600.0
print("DONE: cur =", cur, " expected N_total =", N_total)
print(f"Total hours across all subjects: {total_hours_all:.2f} hours")

# flush
del X_mm
del y_mm

# save meta
meta = {
    "N": int(N_total),
    "T": SEG_LEN,
    "C": int(n_channels),
    "SAMPLE_RATE_LIST": SAMPLE_RATE_LIST,
    "OVERLAP": int(OVERLAP),   # in samples
    "STEP": int(STEP),
    "X_path": X_path,
    "y_path": y_path,
}
with open(meta_path, "w") as f:
    json.dump(meta, f, indent=2)

print("Saved meta:", meta_path)

[PASS 2] Subject: 00001, expected total segments=1163
Original frequency  200.0
Raw data shape  (145600, 19)
Cleaned data shape  (133400, 19)
raw shape: (133400, 19)
fs=200Hz: resampled shape=(133400, 19)
fs=200Hz: segments=666
fs=100Hz: resampled shape=(66700, 19)
fs=100Hz: segments=332
fs=50Hz: resampled shape=(33350, 19)
fs=50Hz: segments=165
-------------------------------------

[PASS 2] Subject: 00002, expected total segments=1674
Original frequency  200.0
Raw data shape  (208600, 19)
Cleaned data shape  (191944, 19)
raw shape: (191944, 19)
fs=200Hz: resampled shape=(191944, 19)
fs=200Hz: segments=958
fs=100Hz: resampled shape=(95972, 19)
fs=100Hz: segments=478
fs=50Hz: resampled shape=(47986, 19)
fs=50Hz: segments=238
-------------------------------------

[PASS 2] Subject: 00003, expected total segments=1078
Original frequency  200.0
Raw data shape  (130200, 19)
Cleaned data shape  (123600, 19)
raw shape: (123600, 19)
fs=200Hz: resampled shape=(123600, 19)
fs=200Hz: segments=617
fs=100Hz: resampled shape=(61800, 19)
fs=100Hz: segments=308
fs=50Hz: resampled shape=(30900, 19)
fs=50Hz: segments=153
-------------------------------------

[PASS 2] Subject: 00004, expected total segments=1331
Original frequency  200.0
Raw data shape  (169400, 19)
Cleaned data shape  (152600, 19)
raw shape: (152600, 19)
fs=200Hz: resampled shape=(152600, 19)
fs=200Hz: segments=762
fs=100Hz: resampled shape=(76300, 19)
fs=100Hz: segments=380
fs=50Hz: resampled shape=(38150, 19)
fs=50Hz: segments=189
-------------------------------------

[PASS 2] Subject: 00005, expected total segments=1387
Original frequency  200.0
Raw data shape  (183400, 19)
Cleaned data shape  (159126, 19)
raw shape: (159126, 19)
fs=200Hz: resampled shape=(159126, 19)
fs=200Hz: segments=794
fs=100Hz: resampled shape=(79563, 19)
fs=100Hz: segments=396
fs=50Hz: resampled shape=(39781, 19)
fs=50Hz: segments=197
-------------------------------------

[PASS 2] Subject: 00006, expected total segments=1310
Original frequency  200.0
Raw data shape  (168000, 19)
Cleaned data shape  (150200, 19)
raw shape: (150200, 19)
fs=200Hz: resampled shape=(150200, 19)
fs=200Hz: segments=750
fs=100Hz: resampled shape=(75100, 19)
fs=100Hz: segments=374
fs=50Hz: resampled shape=(37550, 19)
fs=50Hz: segments=186
-------------------------------------

[PASS 2] Subject: 00007, expected total segments=1435
Original frequency  200.0
Raw data shape  (180600, 19)
Cleaned data shape  (164400, 19)
raw shape: (164400, 19)
fs=200Hz: resampled shape=(164400, 19)
fs=200Hz: segments=821
fs=100Hz: resampled shape=(82200, 19)
fs=100Hz: segments=410
fs=50Hz: resampled shape=(41100, 19)
fs=50Hz: segments=204
-------------------------------------

[PASS 2] Subject: 00008, expected total segments=784
Original frequency  200.0
Raw data shape  (100800, 19)
Cleaned data shape  (90030, 19)
raw shape: (90030, 19)
fs=200Hz: resampled shape=(90030, 19)
fs=200Hz: segments=449
fs=100Hz: resampled shape=(45015, 19)
fs=100Hz: segments=224
fs=50Hz: resampled shape=(22507, 19)
fs=50Hz: segments=111
-------------------------------------

[PASS 2] Subject: 00010, expected total segments=1691
Original frequency  200.0
Raw data shape  (201600, 19)
Cleaned data shape  (193600, 19)
raw shape: (193600, 19)
fs=200Hz: resampled shape=(193600, 19)
fs=200Hz: segments=967
fs=100Hz: resampled shape=(96800, 19)
fs=100Hz: segments=483
fs=50Hz: resampled shape=(48400, 19)
fs=50Hz: segments=241
-------------------------------------

[PASS 2] Subject: 00011, expected total segments=1456
Original frequency  200.0
Raw data shape  (183400, 19)
Cleaned data shape  (166800, 19)
raw shape: (166800, 19)
fs=200Hz: resampled shape=(166800, 19)
fs=200Hz: segments=833
fs=100Hz: resampled shape=(83400, 19)
fs=100Hz: segments=416
fs=50Hz: resampled shape=(41700, 19)
fs=50Hz: segments=207
-------------------------------------

[PASS 2] Subject: 00012, expected total segments=1190
Original frequency  200.0
Raw data shape  (152600, 19)
Cleaned data shape  (136400, 19)
raw shape: (136400, 19)
fs=200Hz: resampled shape=(136400, 19)
fs=200Hz: segments=681
fs=100Hz: resampled shape=(68200, 19)
fs=100Hz: segments=340
fs=50Hz: resampled shape=(34100, 19)
fs=50Hz: segments=169
-------------------------------------

[PASS 2] Subject: 00013, expected total segments=1197
Original frequency  200.0
Raw data shape  (163800, 19)
Cleaned data shape  (137214, 19)
raw shape: (137214, 19)
fs=200Hz: resampled shape=(137214, 19)
fs=200Hz: segments=685
fs=100Hz: resampled shape=(68607, 19)
fs=100Hz: segments=342
fs=50Hz: resampled shape=(34303, 19)
fs=50Hz: segments=170
-------------------------------------

[PASS 2] Subject: 00014, expected total segments=1061
Original frequency  200.0
Raw data shape  (128800, 19)
Cleaned data shape  (121600, 19)
raw shape: (121600, 19)
fs=200Hz: resampled shape=(121600, 19)
fs=200Hz: segments=607
fs=100Hz: resampled shape=(60800, 19)
fs=100Hz: segments=303
fs=50Hz: resampled shape=(30400, 19)
fs=50Hz: segments=151
-------------------------------------

[PASS 2] Subject: 00015, expected total segments=1426
Original frequency  200.0
Raw data shape  (176400, 19)
Cleaned data shape  (163400, 19)
raw shape: (163400, 19)
fs=200Hz: resampled shape=(163400, 19)
fs=200Hz: segments=816
fs=100Hz: resampled shape=(81700, 19)
fs=100Hz: segments=407
fs=50Hz: resampled shape=(40850, 19)
fs=50Hz: segments=203
-------------------------------------

[PASS 2] Subject: 00016, expected total segments=1012
Original frequency  200.0
Raw data shape  (124600, 19)
Cleaned data shape  (116000, 19)
raw shape: (116000, 19)
fs=200Hz: resampled shape=(116000, 19)
fs=200Hz: segments=579
fs=100Hz: resampled shape=(58000, 19)
fs=100Hz: segments=289
fs=50Hz: resampled shape=(29000, 19)
fs=50Hz: segments=144
-------------------------------------

[PASS 2] Subject: 00017, expected total segments=946
Original frequency  200.0
Raw data shape  (121800, 19)
Cleaned data shape  (108600, 19)
raw shape: (108600, 19)
fs=200Hz: resampled shape=(108600, 19)
fs=200Hz: segments=542
fs=100Hz: resampled shape=(54300, 19)
fs=100Hz: segments=270
fs=50Hz: resampled shape=(27150, 19)
fs=50Hz: segments=134
-------------------------------------

[PASS 2] Subject: 00018, expected total segments=1443
Original frequency  200.0
Raw data shape  (176400, 19)
Cleaned data shape  (165400, 19)
raw shape: (165400, 19)
fs=200Hz: resampled shape=(165400, 19)
fs=200Hz: segments=826
fs=100Hz: resampled shape=(82700, 19)
fs=100Hz: segments=412
fs=50Hz: resampled shape=(41350, 19)
fs=50Hz: segments=205
-------------------------------------

[PASS 2] Subject: 00019, expected total segments=945
Original frequency  200.0
Raw data shape  (121800, 19)
Cleaned data shape  (108400, 19)
raw shape: (108400, 19)
fs=200Hz: resampled shape=(108400, 19)
fs=200Hz: segments=541
fs=100Hz: resampled shape=(54200, 19)
fs=100Hz: segments=270
fs=50Hz: resampled shape=(27100, 19)
fs=50Hz: segments=134
-------------------------------------

[PASS 2] Subject: 00020, expected total segments=1285
Original frequency  200.0
Raw data shape  (152600, 19)
Cleaned data shape  (147200, 19)
raw shape: (147200, 19)
fs=200Hz: resampled shape=(147200, 19)
fs=200Hz: segments=735
fs=100Hz: resampled shape=(73600, 19)
fs=100Hz: segments=367
fs=50Hz: resampled shape=(36800, 19)
fs=50Hz: segments=183
-------------------------------------

[PASS 2] Subject: 00021, expected total segments=1470
Original frequency  200.0
Raw data shape  (180600, 19)
Cleaned data shape  (168400, 19)
raw shape: (168400, 19)
fs=200Hz: resampled shape=(168400, 19)
fs=200Hz: segments=841
fs=100Hz: resampled shape=(84200, 19)
fs=100Hz: segments=420
fs=50Hz: resampled shape=(42100, 19)
fs=50Hz: segments=209
-------------------------------------

[PASS 2] Subject: 00022, expected total segments=977
Original frequency  200.0
Raw data shape  (120400, 19)
Cleaned data shape  (112000, 19)
raw shape: (112000, 19)
fs=200Hz: resampled shape=(112000, 19)
fs=200Hz: segments=559
fs=100Hz: resampled shape=(56000, 19)
fs=100Hz: segments=279
fs=50Hz: resampled shape=(28000, 19)
fs=50Hz: segments=139
-------------------------------------

[PASS 2] Subject: 00023, expected total segments=1589
Original frequency  200.0
Raw data shape  (194600, 19)
Cleaned data shape  (182010, 19)
raw shape: (182010, 19)
fs=200Hz: resampled shape=(182010, 19)
fs=200Hz: segments=909
fs=100Hz: resampled shape=(91005, 19)
fs=100Hz: segments=454
fs=50Hz: resampled shape=(45502, 19)
fs=50Hz: segments=226
-------------------------------------

[PASS 2] Subject: 00024, expected total segments=2077
Original frequency  200.0
Raw data shape  (247800, 19)
Cleaned data shape  (237800, 19)
raw shape: (237800, 19)
fs=200Hz: resampled shape=(237800, 19)
fs=200Hz: segments=1188
fs=100Hz: resampled shape=(118900, 19)
fs=100Hz: segments=593
fs=50Hz: resampled shape=(59450, 19)
fs=50Hz: segments=296
-------------------------------------

[PASS 2] Subject: 00025, expected total segments=994
Original frequency  200.0
Raw data shape  (120400, 19)
Cleaned data shape  (114000, 19)
raw shape: (114000, 19)
fs=200Hz: resampled shape=(114000, 19)
fs=200Hz: segments=569
fs=100Hz: resampled shape=(57000, 19)
fs=100Hz: segments=284
fs=50Hz: resampled shape=(28500, 19)
fs=50Hz: segments=141
-------------------------------------

[PASS 2] Subject: 00026, expected total segments=1526
Original frequency  200.0
Raw data shape  (184800, 19)
Cleaned data shape  (174854, 19)
raw shape: (174854, 19)
fs=200Hz: resampled shape=(174854, 19)
fs=200Hz: segments=873
fs=100Hz: resampled shape=(87427, 19)
fs=100Hz: segments=436
fs=50Hz: resampled shape=(43713, 19)
fs=50Hz: segments=217
-------------------------------------

[PASS 2] Subject: 00027, expected total segments=1498
Original frequency  200.0
Raw data shape  (180600, 19)
Cleaned data shape  (171600, 19)
raw shape: (171600, 19)
fs=200Hz: resampled shape=(171600, 19)
fs=200Hz: segments=857
fs=100Hz: resampled shape=(85800, 19)
fs=100Hz: segments=428
fs=50Hz: resampled shape=(42900, 19)
fs=50Hz: segments=213
-------------------------------------

[PASS 2] Subject: 00028, expected total segments=1624
Original frequency  200.0
Raw data shape  (204400, 19)
Cleaned data shape  (186000, 19)
raw shape: (186000, 19)
fs=200Hz: resampled shape=(186000, 19)
fs=200Hz: segments=929
fs=100Hz: resampled shape=(93000, 19)
fs=100Hz: segments=464
fs=50Hz: resampled shape=(46500, 19)
fs=50Hz: segments=231
-------------------------------------

[PASS 2] Subject: 00029, expected total segments=1384
Original frequency  200.0
Raw data shape  (169400, 19)
Cleaned data shape  (158600, 19)
raw shape: (158600, 19)
fs=200Hz: resampled shape=(158600, 19)
fs=200Hz: segments=792
fs=100Hz: resampled shape=(79300, 19)
fs=100Hz: segments=395
fs=50Hz: resampled shape=(39650, 19)
fs=50Hz: segments=197
-------------------------------------

[PASS 2] Subject: 00030, expected total segments=1488
Original frequency  200.0
Raw data shape  (183400, 19)
Cleaned data shape  (170400, 19)
raw shape: (170400, 19)
fs=200Hz: resampled shape=(170400, 19)
fs=200Hz: segments=851
fs=100Hz: resampled shape=(85200, 19)
fs=100Hz: segments=425
fs=50Hz: resampled shape=(42600, 19)
fs=50Hz: segments=212
-------------------------------------

[PASS 2] Subject: 00031, expected total segments=1435
Original frequency  200.0
Raw data shape  (175000, 19)
Cleaned data shape  (164400, 19)
raw shape: (164400, 19)
fs=200Hz: resampled shape=(164400, 19)
fs=200Hz: segments=821
fs=100Hz: resampled shape=(82200, 19)
fs=100Hz: segments=410
fs=50Hz: resampled shape=(41100, 19)
fs=50Hz: segments=204
-------------------------------------

[PASS 2] Subject: 00032, expected total segments=1019
Original frequency  200.0
Raw data shape  (124600, 19)
Cleaned data shape  (116800, 19)
raw shape: (116800, 19)
fs=200Hz: resampled shape=(116800, 19)
fs=200Hz: segments=583
fs=100Hz: resampled shape=(58400, 19)
fs=100Hz: segments=291
fs=50Hz: resampled shape=(29200, 19)
fs=50Hz: segments=145
-------------------------------------

[PASS 2] Subject: 00033, expected total segments=1534
Original frequency  200.0
Raw data shape  (190400, 19)
Cleaned data shape  (175942, 19)
raw shape: (175942, 19)
fs=200Hz: resampled shape=(175942, 19)
fs=200Hz: segments=878
fs=100Hz: resampled shape=(87971, 19)
fs=100Hz: segments=438
fs=50Hz: resampled shape=(43985, 19)
fs=50Hz: segments=218
-------------------------------------

[PASS 2] Subject: 00034, expected total segments=1107
Original frequency  200.0
Raw data shape  (135800, 19)
Cleaned data shape  (127172, 19)
raw shape: (127172, 19)
fs=200Hz: resampled shape=(127172, 19)
fs=200Hz: segments=634
fs=100Hz: resampled shape=(63586, 19)
fs=100Hz: segments=316
fs=50Hz: resampled shape=(31793, 19)
fs=50Hz: segments=157
-------------------------------------

[PASS 2] Subject: 00035, expected total segments=1484
Original frequency  200.0
Raw data shape  (182000, 19)
Cleaned data shape  (170000, 19)
raw shape: (170000, 19)
fs=200Hz: resampled shape=(170000, 19)
fs=200Hz: segments=849
fs=100Hz: resampled shape=(85000, 19)
fs=100Hz: segments=424
fs=50Hz: resampled shape=(42500, 19)
fs=50Hz: segments=211
-------------------------------------

[PASS 2] Subject: 00036, expected total segments=1261
Original frequency  200.0
Raw data shape  (161000, 19)
Cleaned data shape  (144600, 19)
raw shape: (144600, 19)
fs=200Hz: resampled shape=(144600, 19)
fs=200Hz: segments=722
fs=100Hz: resampled shape=(72300, 19)
fs=100Hz: segments=360
fs=50Hz: resampled shape=(36150, 19)
fs=50Hz: segments=179
-------------------------------------

[PASS 2] Subject: 00037, expected total segments=1387
Original frequency  200.0
Raw data shape  (169400, 19)
Cleaned data shape  (159000, 19)
raw shape: (159000, 19)
fs=200Hz: resampled shape=(159000, 19)
fs=200Hz: segments=794
fs=100Hz: resampled shape=(79500, 19)
fs=100Hz: segments=396
fs=50Hz: resampled shape=(39750, 19)
fs=50Hz: segments=197
-------------------------------------

[PASS 2] Subject: 00038, expected total segments=1562
Original frequency  200.0
Raw data shape  (187600, 19)
Cleaned data shape  (179000, 19)
raw shape: (179000, 19)
fs=200Hz: resampled shape=(179000, 19)
fs=200Hz: segments=894
fs=100Hz: resampled shape=(89500, 19)
fs=100Hz: segments=446
fs=50Hz: resampled shape=(44750, 19)
fs=50Hz: segments=222
-------------------------------------

[PASS 2] Subject: 00039, expected total segments=1233
Original frequency  200.0
Raw data shape  (163800, 19)
Cleaned data shape  (141400, 19)
raw shape: (141400, 19)
fs=200Hz: resampled shape=(141400, 19)
fs=200Hz: segments=706
fs=100Hz: resampled shape=(70700, 19)
fs=100Hz: segments=352
fs=50Hz: resampled shape=(35350, 19)
fs=50Hz: segments=175
-------------------------------------

[PASS 2] Subject: 00040, expected total segments=1313
Original frequency  200.0
Raw data shape  (161000, 19)
Cleaned data shape  (150400, 19)
raw shape: (150400, 19)
fs=200Hz: resampled shape=(150400, 19)
fs=200Hz: segments=751
fs=100Hz: resampled shape=(75200, 19)
fs=100Hz: segments=375
fs=50Hz: resampled shape=(37600, 19)
fs=50Hz: segments=187
-------------------------------------

[PASS 2] Subject: 00041, expected total segments=978
Original frequency  200.0
Raw data shape  (120400, 19)
Cleaned data shape  (112200, 19)
raw shape: (112200, 19)
fs=200Hz: resampled shape=(112200, 19)
fs=200Hz: segments=560
fs=100Hz: resampled shape=(56100, 19)
fs=100Hz: segments=279
fs=50Hz: resampled shape=(28050, 19)
fs=50Hz: segments=139
-------------------------------------

[PASS 2] Subject: 00042, expected total segments=1400
Original frequency  200.0
Raw data shape  (182000, 19)
Cleaned data shape  (160400, 19)
raw shape: (160400, 19)
fs=200Hz: resampled shape=(160400, 19)
fs=200Hz: segments=801
fs=100Hz: resampled shape=(80200, 19)
fs=100Hz: segments=400
fs=50Hz: resampled shape=(40100, 19)
fs=50Hz: segments=199
-------------------------------------

[PASS 2] Subject: 00043, expected total segments=1589
Original frequency  200.0
Raw data shape  (198800, 19)
Cleaned data shape  (182086, 19)
raw shape: (182086, 19)
fs=200Hz: resampled shape=(182086, 19)
fs=200Hz: segments=909
fs=100Hz: resampled shape=(91043, 19)
fs=100Hz: segments=454
fs=50Hz: resampled shape=(45521, 19)
fs=50Hz: segments=226
-------------------------------------

[PASS 2] Subject: 00044, expected total segments=1548
Original frequency  200.0
Raw data shape  (187600, 19)
Cleaned data shape  (177400, 19)
raw shape: (177400, 19)
fs=200Hz: resampled shape=(177400, 19)
fs=200Hz: segments=886
fs=100Hz: resampled shape=(88700, 19)
fs=100Hz: segments=442
fs=50Hz: resampled shape=(44350, 19)
fs=50Hz: segments=220
-------------------------------------

[PASS 2] Subject: 00045, expected total segments=1565
Original frequency  200.0
Raw data shape  (194600, 19)
Cleaned data shape  (179200, 19)
raw shape: (179200, 19)
fs=200Hz: resampled shape=(179200, 19)
fs=200Hz: segments=895
fs=100Hz: resampled shape=(89600, 19)
fs=100Hz: segments=447
fs=50Hz: resampled shape=(44800, 19)
fs=50Hz: segments=223
-------------------------------------

[PASS 2] Subject: 00046, expected total segments=1408
Original frequency  200.0
Raw data shape  (170800, 19)
Cleaned data shape  (161400, 19)
raw shape: (161400, 19)
fs=200Hz: resampled shape=(161400, 19)
fs=200Hz: segments=806
fs=100Hz: resampled shape=(80700, 19)
fs=100Hz: segments=402
fs=50Hz: resampled shape=(40350, 19)
fs=50Hz: segments=200
-------------------------------------

[PASS 2] Subject: 00047, expected total segments=2091
Original frequency  200.0
Raw data shape  (249200, 19)
Cleaned data shape  (239400, 19)
raw shape: (239400, 19)
fs=200Hz: resampled shape=(239400, 19)
fs=200Hz: segments=1196
fs=100Hz: resampled shape=(119700, 19)
fs=100Hz: segments=597
fs=50Hz: resampled shape=(59850, 19)
fs=50Hz: segments=298
-------------------------------------

[PASS 2] Subject: 00048, expected total segments=1337
Original frequency  200.0
Raw data shape  (170800, 19)
Cleaned data shape  (153200, 19)
raw shape: (153200, 19)
fs=200Hz: resampled shape=(153200, 19)
fs=200Hz: segments=765
fs=100Hz: resampled shape=(76600, 19)
fs=100Hz: segments=382
fs=50Hz: resampled shape=(38300, 19)
fs=50Hz: segments=190
-------------------------------------

[PASS 2] Subject: 00049, expected total segments=1076
Original frequency  200.0
Raw data shape  (144200, 19)
Cleaned data shape  (123400, 19)
raw shape: (123400, 19)
fs=200Hz: resampled shape=(123400, 19)
fs=200Hz: segments=616
fs=100Hz: resampled shape=(61700, 19)
fs=100Hz: segments=307
fs=50Hz: resampled shape=(30850, 19)
fs=50Hz: segments=153
-------------------------------------

[PASS 2] Subject: 00050, expected total segments=1657
Original frequency  200.0
Raw data shape  (197400, 19)
Cleaned data shape  (189800, 19)
raw shape: (189800, 19)
fs=200Hz: resampled shape=(189800, 19)
fs=200Hz: segments=948
fs=100Hz: resampled shape=(94900, 19)
fs=100Hz: segments=473
fs=50Hz: resampled shape=(47450, 19)
fs=50Hz: segments=236
-------------------------------------

[PASS 2] Subject: 00051, expected total segments=1055
Original frequency  200.0
Raw data shape  (131600, 19)
Cleaned data shape  (121000, 19)
raw shape: (121000, 19)
fs=200Hz: resampled shape=(121000, 19)
fs=200Hz: segments=604
fs=100Hz: resampled shape=(60500, 19)
fs=100Hz: segments=301
fs=50Hz: resampled shape=(30250, 19)
fs=50Hz: segments=150
-------------------------------------

[PASS 2] Subject: 00052, expected total segments=1090
Original frequency  200.0
Raw data shape  (159600, 19)
Cleaned data shape  (125000, 19)
raw shape: (125000, 19)
fs=200Hz: resampled shape=(125000, 19)
fs=200Hz: segments=624
fs=100Hz: resampled shape=(62500, 19)
fs=100Hz: segments=311
fs=50Hz: resampled shape=(31250, 19)
fs=50Hz: segments=155
-------------------------------------

[PASS 2] Subject: 00053, expected total segments=1446
Original frequency  200.0
Raw data shape  (180600, 19)
Cleaned data shape  (165600, 19)
raw shape: (165600, 19)
fs=200Hz: resampled shape=(165600, 19)
fs=200Hz: segments=827
fs=100Hz: resampled shape=(82800, 19)

## Load and check the processed data

In [18]:
import json
import numpy as np

# load meta information
meta_path = meta_path  # if you already have meta_path in current notebook
with open(meta_path, "r") as f:
    meta = json.load(f)

N = meta["N"]
T = meta["T"]          # SEG_LEN
C = meta["C"]
X_path = meta["X_path"]
y_path = meta["y_path"]

print("Meta:")
print("  N =", N)
print("  T =", T)
print("  C =", C)
print("  X_path =", X_path)
print("  y_path =", y_path)
print("-------------------------------------")

# open memmap
X_mm = np.memmap(X_path, dtype='float32', mode='r', shape=(N, T, C))
y_mm = np.memmap(y_path, dtype='float32', mode='r', shape=(N, 3))

# subject_id is stored in y[:, 1]
subject_ids = np.unique(y_mm[:, 1]).astype(int)

for sid in sorted(subject_ids):
    # find all indices for this subject
    idx = np.where(y_mm[:, 1] == sid)[0]

    # compute shapes logically (do not load all X into memory)
    n_seg = len(idx)
    x_shape = (n_seg, T, C)    # logical X shape for this subject
    y_shape = (n_seg, 3)       # logical y shape for this subject

    # get sampling rates for all segments of this subject
    fs_subject = y_mm[idx, 2]  # shape (n_seg,)


    print(f"Subject ID {sid:03d}: X shape={x_shape}, y shape={y_shape}")

# option: delete memmap views
del X_mm, y_mm

Meta:
  N = 1773814
  T = 400
  C = 19
  X_path = Processed\L400\CAUEEG\X.dat
  y_path = Processed\L400\CAUEEG\y.dat
-------------------------------------
Subject ID 001: X shape=(1163, 400, 19), y shape=(1163, 3)
Subject ID 002: X shape=(1674, 400, 19), y shape=(1674, 3)
Subject ID 003: X shape=(1078, 400, 19), y shape=(1078, 3)
Subject ID 004: X shape=(1331, 400, 19), y shape=(1331, 3)
Subject ID 005: X shape=(1387, 400, 19), y shape=(1387, 3)
Subject ID 006: X shape=(1310, 400, 19), y shape=(1310, 3)
Subject ID 007: X shape=(1435, 400, 19), y shape=(1435, 3)
Subject ID 008: X shape=(784, 400, 19), y shape=(784, 3)
Subject ID 010: X shape=(1691, 400, 19), y shape=(1691, 3)
Subject ID 011: X shape=(1456, 400, 19), y shape=(1456, 3)
Subject ID 012: X shape=(1190, 400, 19), y shape=(1190, 3)
Subject ID 013: X shape=(1197, 400, 19), y shape=(1197, 3)
Subject ID 014: X shape=(1061, 400, 19), y shape=(1061, 3)
Subject ID 015: X shape=(1426, 400, 19), y shape=(1426, 3)
Subject ID 016: X shape=(1012, 400, 19), y shape=(1012, 3)
Subject ID 017: X shape=(946, 400, 19), y shape=(946, 3)
Subject ID 018: X shape=(1443, 400, 19), y shape=(1443, 3)
Subject ID 019: X shape=(945, 400, 19), y shape=(945, 3)
Subject ID 020: X shape=(1285, 400, 19), y shape=(1285, 3)
Subject ID 021: X shape=(1470, 400, 19), y shape=(1470, 3)
Subject ID 022: X shape=(977, 400, 19), y shape=(977, 3)
Subject ID 023: X shape=(1589, 400, 19), y shape=(1589, 3)
Subject ID 024: X shape=(2077, 400, 19), y shape=(2077, 3)
Subject ID 025: X shape=(994, 400, 19), y shape=(994, 3)
Subject ID 026: X shape=(1526, 400, 19), y shape=(1526, 3)
Subject ID 027: X shape=(1498, 400, 19), y shape=(1498, 3)
Subject ID 028: X shape=(1624, 400, 19), y shape=(1624, 3)
Subject ID 029: X shape=(1384, 400, 19), y shape=(1384, 3)
Subject ID 030: X shape=(1488, 400, 19), y shape=(1488, 3)
Subject ID 031: X shape=(1435, 400, 19), y shape=(1435, 3)
Subject ID 032: X shape=(1019, 400, 19), y shape=(1019, 3)
Subject ID 033: X shape=(1534, 400, 19), y shape=(1534, 3)
Subject ID 034: X shape=(1107, 400, 19), y shape=(1107, 3)
Subject ID 035: X shape=(1484, 400, 19), y shape=(1484, 3)
Subject ID 036: X shape=(1261, 400, 19), y shape=(1261, 3)
Subject ID 037: X shape=(1387, 400, 19), y shape=(1387, 3)
Subject ID 038: X shape=(1562, 400, 19), y shape=(1562, 3)
Subject ID 039: X shape=(1233, 400, 19), y shape=(1233, 3)
Subject ID 040: X shape=(1313, 400, 19), y shape=(1313, 3)
Subject ID 041: X shape=(978, 400, 19), y shape=(978, 3)
Subject ID 042: X shape=(1400, 400, 19), y shape=(1400, 3)
Subject ID 043: X shape=(1589, 400, 19), y shape=(1589, 3)
Subject ID 044: X shape=(1548, 400, 19), y shape=(1548, 3)
Subject ID 045: X shape=(1565, 400, 19), y shape=(1565, 3)
Subject ID 046: X shape=(1408, 400, 19), y shape=(1408, 3)
Subject ID 047: X shape=(2091, 400, 19), y shape=(2091, 3)
Subject ID 048: X shape=(1337, 400, 19), y shape=(1337, 3)
Subject ID 049: X shape=(1076, 400, 19), y shape=(1076, 3)
Subject ID 050: X shape=(1657, 400, 19), y shape=(1657, 3)
Subject ID 051: X shape=(1055, 400, 19), y shape=(1055, 3)
Subject ID 052: X shape=(1090, 400, 19), y shape=(1090, 3)
Subject ID 053: X shape=(1446, 400, 19), y shape=(1446, 3)
Subject ID 054: X shape=(1299, 400, 19), y shape=(1299, 3)
Subject ID 055: X shape=(1701, 400, 19), y shape=(1701, 3)
Subject ID 056: X shape=(774, 400, 19), y shape=(774, 3)
Subject ID 057: X shape=(1391, 400, 19), y shape=(1391, 3)
Subject ID 058: X shape=(841, 400, 19), y shape=(841, 3)
Subject ID 059: X shape=(1397, 400, 19), y shape=(1397, 3)
Subject ID 060: X shape=(1726, 400, 19), y shape=(1726, 3)
Subject ID 061: X shape=(1435, 400, 19), y shape=(1435, 3)
Subject ID 062: X shape=(1072, 400, 19), y shape=(1072, 3)
Subject ID 063: X shape=(1159, 400, 19), y shape=(1159, 3)
Subject ID 064: X shape=(1237, 400, 19), y shape=(1237, 3)
Subject ID 065: X shape=(1358, 400, 19), y shape=(1358, 3)
Subject ID 066: X shape=(1376, 400, 19), y shape=(1376, 3)
Subject ID 067: X shape=(1323, 400, 19), y shape=(1323, 3)
Subject ID 068: X shape=(1422, 400, 19), y shape=(1422, 3)
Subject ID 069: X shape=(1440, 400, 19), y shape=(1440, 3)
Subject ID 070: X shape=(1376, 400, 19), y shape=(1376, 3)
Subject ID 071: X shape=(1405, 400, 19), y shape=(1405, 3)
Subject ID 072: X shape=(1531, 400, 19), y shape=(1531, 3)
Subject ID 073: X shape=(1005, 400, 19), y shape=(1005, 3)
Subject ID 074: X shape=(981, 400, 19), y shape=(981, 3)
Subject ID 075: X shape=(978, 400, 19), y shape=(978, 3)
Subject ID 076: X shape=(1316, 400, 19), y shape=(1316, 3)
Subject ID 077: X shape=(1538, 400, 19), y shape=(1538, 3)
Subject ID 078: X shape=(1559, 400, 19), y shape=(1559, 3)
Subject ID 079: X shape=(1394, 400, 19), y shape=(1394, 3)
Subject ID 080: X shape=(1163, 400, 19), y shape=(1163, 3)
Subject ID 081: X shape=(1128, 400, 19), y shape=(1128, 3)
Subject ID 082: X shape=(1761, 400, 19), y shape=(1761, 3)
Subject ID 083: X shape=(1526, 400, 19), y shape=(1526, 3)
Subject ID 084: X shape=(950, 400, 19), y shape=(950, 3)
Subject ID 085: X shape=(980, 400, 19), y shape=(980, 3)
Subject ID 086: X shape=(722, 400, 19), y shape=(722, 3)
Subject ID 087: X shape=(1005, 400, 19), y shape=(1005, 3)
Subject ID 088: X shape=(1365, 400, 19), y shape=(1365, 3)
Subject ID 089: X shape=(1358, 400, 19), y shape=(1358, 3)
Subject ID 090: X shape=(894, 400, 19), y shape=(894, 3)
Subject ID 091: X shape=(1376, 400, 19), y shape=(1376, 3)
Subject ID 092: X shape=(1292, 400, 19), y shape=(1292, 3)
Subject ID 093: X shape=(1016, 400, 19), y shape=(1016, 3)
Subject ID 094: X shape=(1086, 400, 19), y shape=(1086, 3)
Subject ID 095: X shape=(1153, 400, 19), y shape=(1153, 3)
Subject ID 096: X shape=(1509, 400, 19), y shape=(1509, 3)
Subject ID 097: X shape=(1293, 400, 19), y shape=(1293, 3)
Subject ID 098: X shape=(1418, 400, 19), y shape=(1418, 3)
Subject ID 099: X shape=(995, 400, 19), y shape=(995, 3)
Subject ID 100: X shape=(977, 400, 19), y shape=(977, 3)
Subject ID 101: X shape=(987, 400, 19), y shape=(987, 3)
Subject ID 102: X shape=(1442, 400, 19), y shape=(1442, 3)
Subject ID 103: X shape=(952, 400, 19), y shape=(952, 3)
Subject ID 104: X shape=(1523, 400, 19), y shape=(1523, 3)
Subject ID 105: X shape=(1190, 400, 19), y shape=(1190, 3)
Subject ID 106: X shape=(1440, 400, 19), y shape=(1440, 3)
Subject ID 107: X shape=(1166, 400, 19), y shape=(1166, 3)
Subject ID 108: X shape=(1908, 400, 19), y shape=(1908, 3)
Subject ID 109: X shape=(1009, 400, 19), y shape=(1009, 3)
Subject ID 110: X shape=(2150, 400, 19), y shape=(2150, 3)
Subject ID 111: X shape=(1051, 400, 19), y shape=(1051, 3)
Subject ID 112: X shape=(984, 400, 19), y shape=(984, 3)
Subject ID 113: X shape=(1022, 400, 19), y shape=(1022, 3)
Subject ID 114: X shape=(1366, 400, 19), y shape=(1366, 3)
Subject ID 115: X shape=(1418, 400, 19), y shape=(1418, 3)
Subject ID 116: X shape=(1349, 400, 19), y shape=(1349, 3)
Subject ID 117: X shape=(1524, 400, 19), y shape=(1524, 3)
Subject ID 118: X shape=(1338, 400, 19), y shape=(1338, 3)
Subject ID 119: X shape=(1418, 400, 19), y shape=(1418, 3)
Subject ID 120: X shape=(1531, 400, 19), y shape=(1531, 3)
Subject ID 121: X shape=(1104, 400, 19), y shape=(1104, 3)
Subject ID 122: X shape=(992, 400, 19), y shape=(992, 3)
Subject ID 123: X shape=(1443, 400, 19), y shape=(1443, 3)
Subject ID 124: X shape=(977, 400, 19), y shape=(977, 3)
Subject ID 125: X shape=(991, 400, 19), y shape=(991, 3)
Subject ID 126: X shape=(1586, 400, 19), y shape=(1586, 3)
Subject ID 127: X shape=(1068, 400, 19), y shape=(1068, 3)
Subject ID 128: X shape=(1303, 400, 19), y shape=(1303, 3)
Subject ID 129: X shape=(1447, 400, 19), y shape=(1447, 3)
Subject ID 130: X shape=(1419, 400, 19), y shape=(1419, 3)
Subject ID 131: X shape=(1538, 400, 19), y shape=(1538, 3)
Subject ID 132: X shape=(1342, 400, 19), y shape=(1342, 3)
Subject ID 133: X shape=(1293, 400, 19), y shape=(1293, 3)
Subject ID 134: X shape=(1429, 400, 19), y shape=(1429, 3)
Subject ID 135: X shape=(1436, 400, 19), y shape=(1436, 3)
Subject ID 136: X shape=(1538, 400, 19), y shape=(1538, 3)
Subject ID 137: X shape=(1131, 400, 19), y shape=(1131, 3)
Subject ID 138: X shape=(980, 400, 19), y shape=(980, 3)
Subject ID 139: X shape=(1377, 400, 19), y shape=(1377, 3)
Subject ID 140: X shape=(847, 400, 19), y shape=(847, 3)
Subject ID 141: X shape=(1362, 400, 19), y shape=(1362, 3)
Subject ID 142: X shape=(858, 400, 19), y shape=(858, 3)
Subject ID 143: X shape=(1334, 400, 19), y shape=(1334, 3)
Subject ID 144: X shape=(1341, 400, 19), y shape=(1341, 3)
Subject ID 145: X shape=(1446, 400, 19), y shape=(1446, 3)
Subject ID 146: X shape=(736, 400, 19), y shape=(736, 3)
Subject ID 147: X shape=(1335, 400, 19), y shape=(1335, 3)
Subject ID 148: X shape=(2147, 400, 19), y shape=(2147, 3)
Subject ID 149: X shape=(980, 400, 19), y shape=(980, 3)
Subject ID 150: X shape=(977, 400, 19), y shape=(977, 3)
Subject ID 151: X shape=(1086, 400, 19), y shape=(1086, 3)
Subject ID 152: X shape=(1447, 400, 19), y shape=(1447, 3)
Subject ID 153: X shape=(980, 400, 19), y shape=(980, 3)
Subject ID 154: X shape=(1422, 400, 19), y shape=(1422, 3)
Subject ID 155: X shape=(1202, 400, 19), y shape=(1202, 3)
Subject ID 156: X shape=(1051, 400, 19), y shape=(1051, 3)
Subject ID 157: X shape=(1057, 400, 19), y shape=(1057, 3)
Subject ID 158: X shape=(1027, 400, 19), y shape=(1027, 3)
Subject ID 159: X shape=(729, 400, 19), y shape=(729, 3)
Subject ID 160: X shape=(984, 400, 19), y shape=(984, 3)
Subject ID 161: X shape=(977, 400, 19), y shape=(977, 3)
Subject ID 162: X shape=(984, 400, 19), y shape=(984, 3)
Subject ID 163: X shape=(977, 400, 19), y shape=(977, 3)
Subject ID 164: X shape=(1065, 400, 19), y shape=(1065, 3)
Subject ID 165: X shape=(1023, 400, 19), y shape=(1023, 3)
Subject ID 166: X shape=(984, 400, 19), y shape=(984, 3)
Subject ID 167: X shape=(1033, 400, 19), y shape=(1033, 3)
Subject ID 168: X shape=(1611, 400, 19), y shape=(1611, 3)
Subject ID 169: X shape=(1505, 400, 19), y shape=(1505, 3)
Subject ID 170: X shape=(690, 400, 19), y shape=(690, 3)
Subject ID 171: X shape=(1594, 400, 19), y shape=(1594, 3)
Subject ID 172: X shape=(985, 400, 19), y shape=(985, 3)
Subject ID 173: X shape=(1051, 400, 19), y shape=(1051, 3)
Subject ID 174: X shape=(1215, 400, 19), y shape=(1215, 3)
Subject ID 175: X shape=(1384, 400, 19), y shape=(1384, 3)
Subject ID 176: X shape=(1548, 400, 19), y shape=(1548, 3)
Subject ID 177: X shape=(1391, 400, 19), y shape=(1391, 3)
Subject ID 178: X shape=(1293, 400, 19), y shape=(1293, 3)
Subject ID 179: X shape=(1012, 400, 19), y shape=(1012, 3)
Subject ID 180: X shape=(1237, 400, 19), y shape=(1237, 3)
Subject ID 181: X shape=(1338, 400, 19), y shape=(1338, 3)
Subject ID 182: X shape=(1572, 400, 19), y shape=(1572, 3)
Subject ID 183: X shape=(1484, 400, 19), y shape=(1484, 3)
Subject ID 184: X shape=(1089, 400, 19), y shape=(1089, 3)
Subject ID 185: X shape=(994, 400, 19), y shape=(994, 3)
Subject ID 186: X shape=(1429, 400, 19), y shape=(1429, 3)
Subject ID 187: X shape=(1372, 400, 19), y shape=(1372, 3)
Subject ID 188: X shape=(1428, 400, 19), y shape=(1428, 3)
Subject ID 189: X shape=(1051, 400, 19), y shape=(1051, 3)
Subject ID 190: X shape=(998, 400, 19), y shape=(998, 3)
Subject ID 191: X shape=(1555, 400, 19), y shape=(1555, 3)
Subject ID 192: X shape=(1034, 400, 19), y shape=(1034, 3)
Subject ID 193: X shape=(791, 400, 19), y shape=(791, 3)
Subject ID 194: X shape=(1075, 400, 19), y shape=(1075, 3)
Subject ID 195: X shape=(1334, 400, 19), y shape=(1334, 3)
Subject ID 196: X shape=(1393, 400, 19), y shape=(1393, 3)
Subject ID 197: X shape=(1041, 400, 19), y shape=(1041, 3)
Subject ID 198: X shape=(1271, 400, 19), y shape=(1271, 3)
Subject ID 199: X shape=(988, 400, 19), y shape=(988, 3)
Subject ID 200: X shape=(1526, 400, 19), y shape=(1526, 3)
Subject ID 201: X shape=(1051, 400, 19), y shape=(1051, 3)
Subject ID 202: X shape=(1356, 400, 19), y shape=(1356, 3)
Subject ID 203: X shape=(1383, 400, 19), y shape=(1383, 3)
Subject ID 204: X shape=(1530, 400, 19), y shape=(1530, 3)
Subject ID 205: X shape=(1523, 400, 19), y shape=(1523, 3)
Subject ID 206: X shape=(1428, 400, 19), y shape=(1428, 3)
Subject ID 207: X shape=(992, 400, 19), y shape=(992, 3)
Subject ID 208: X shape=(985, 400, 19), y shape=(985, 3)
Subject ID 209: X shape=(593, 400, 19), y shape=(593, 3)
Subject ID 210: X shape=(1440, 400, 19), y shape=(1440, 3)
Subject ID 211: X shape=(1090, 400, 19), y shape=(1090, 3)
Subject ID 212: X shape=(1146, 400, 19), y shape=(1146, 3)
Subject ID 213: X shape=(1083, 400, 19), y shape=(1083, 3)
Subject ID 214: X shape=(1572, 400, 19), y shape=(1572, 3)
Subject ID 215: X shape=(1293, 400, 19), y shape=(1293, 3)
Subject ID 216: X shape=(1498, 400, 19), y shape=(1498, 3)
Subject ID 217: X shape=(1496, 400, 19), y shape=(1496, 3)
Subject ID 218: X shape=(1166, 400, 19), y shape=(1166, 3)
Subject ID 219: X shape=(1590, 400, 19), y shape=(1590, 3)
Subject ID 220: X shape=(1296, 400, 19), y shape=(1296, 3)
Subject ID 221: X shape=(1208, 400, 19), y shape=(1208, 3)
Subject ID 222: X shape=(1335, 400, 19), y shape=(1335, 3)
Subject ID 223: X shape=(1617, 400, 19), y shape=(1617, 3)
Subject ID 224: X shape=(1561, 400, 19), y shape=(1561, 3)
Subject ID 225: X shape=(1408, 400, 19), y shape=(1408, 3)
Subject ID 226: X shape=(1463, 400, 19), y shape=(1463, 3)
Subject ID 227: X shape=(1569, 400, 19), y shape=(1569, 3)
Subject ID 228: X shape=(1370, 400, 19), y shape=(1370, 3)
Subject ID 229: X shape=(1344, 400, 19), y shape=(1344, 3)
Subject ID 230: X shape=(936, 400, 19), y shape=(936, 3)
Subject ID 231: X shape=(1936, 400, 19), y shape=(1936, 3)
Subject ID 232: X shape=(1450, 400, 19), y shape=(1450, 3)
Subject ID 233: X shape=(1561, 400, 19), y shape=(1561, 3)
Subject ID 234: X shape=(1421, 400, 19), y shape=(1421, 3)
Subject ID 235: X shape=(1981, 400, 19), y shape=(1981, 3)
Subject ID 236: X shape=(1334, 400, 19), y shape=(1334, 3)
Subject ID 237: X shape=(977, 400, 19), y shape=(977, 3)
Subject ID 238: X shape=(994, 400, 19), y shape=(994, 3)
Subject ID 239: X shape=(1316, 400, 19), y shape=(1316, 3)
Subject ID 240: X shape=(1467, 400, 19), y shape=(1467, 3)
Subject ID 241: X shape=(1722, 400, 19), y shape=(1722, 3)
Subject ID 242: X shape=(1495, 400, 19), y shape=(1495, 3)
Subject ID 243: X shape=(1321, 400, 19), y shape=(1321, 3)
Subject ID 244: X shape=(1496, 400, 19), y shape=(1496, 3)
Subject ID 245: X shape=(1551, 400, 19), y shape=(1551, 3)
Subject ID 246: X shape=(1188, 400, 19), y shape=(1188, 3)
Subject ID 247: X shape=(1226, 400, 19), y shape=(1226, 3)
Subject ID 248: X shape=(742, 400, 19), y shape=(742, 3)
Subject ID 249: X shape=(1478, 400, 19), y shape=(1478, 3)
Subject ID 250: X shape=(1446, 400, 19), y shape=(1446, 3)
Subject ID 251: X shape=(1048, 400, 19), y shape=(1048, 3)
Subject ID 252: X shape=(1530, 400, 19), y shape=(1530, 3)
Subject ID 253: X shape=(1334, 400, 19), y shape=(1334, 3)
Subject ID 254: X shape=(1418, 400, 19), y shape=(1418, 3)
Subject ID 255: X shape=(980, 400, 19), y shape=(980, 3)
Subject ID 256: X shape=(812, 400, 19), y shape=(812, 3)
Subject ID 257: X shape=(1274, 400, 19), y shape=(1274, 3)
Subject ID 258: X shape=(1065, 400, 19), y shape=(1065, 3)
Subject ID 259: X shape=(627, 400, 19), y shape=(627, 3)
Subject ID 260: X shape=(1394, 400, 19), y shape=(1394, 3)
Subject ID 261: X shape=(1335, 400, 19), y shape=(1335, 3)
Subject ID 262: X shape=(1064, 400, 19), y shape=(1064, 3)
Subject ID 263: X shape=(1484, 400, 19), y shape=(1484, 3)
Subject ID 264: X shape=(1222, 400, 19), y shape=(1222, 3)
Subject ID 265: X shape=(1316, 400, 19), y shape=(1316, 3)
Subject ID 266: X shape=(1370, 400, 19), y shape=(1370, 3)
Subject ID 267: X shape=(613, 400, 19), y shape=(613, 3)
Subject ID 268: X shape=(1446, 400, 19), y shape=(1446, 3)
Subject ID 269: X shape=(984, 400, 19), y shape=(984, 3)
Subject ID 270: X shape=(994, 400, 19), y shape=(994, 3)
Subject ID 271: X shape=(1247, 400, 19), y shape=(1247, 3)
Subject ID 272: X shape=(1408, 400, 19), y shape=(1408, 3)
Subject ID 273: X shape=(1152, 400, 19), y shape=(1152, 3)
Subject ID 274: X shape=(1146, 400, 19), y shape=(1146, 3)
Subject ID 275: X shape=(1512, 400, 19), y shape=(1512, 3)
Subject ID 276: X shape=(1573, 400, 19), y shape=(1573, 3)
Subject ID 277: X shape=(1873, 400, 19), y shape=(1873, 3)
Subject ID 278: X shape=(994, 400, 19), y shape=(994, 3)
Subject ID 279: X shape=(943, 400, 19), y shape=(943, 3)
Subject ID 280: X shape=(1390, 400, 19), y shape=(1390, 3)
Subject ID 281: X shape=(981, 400, 19), y shape=(981, 3)
Subject ID 282: X shape=(1415, 400, 19), y shape=(1415, 3)
Subject ID 283: X shape=(1496, 400, 19), y shape=(1496, 3)
Subject ID 284: X shape=(1456, 400, 19), y shape=(1456, 3)
Subject ID 285: X shape=(988, 400, 19), y shape=(988, 3)
Subject ID 286: X shape=(1464, 400, 19), y shape=(1464, 3)
Subject ID 288: X shape=(946, 400, 19), y shape=(946, 3)
Subject ID 289: X shape=(1372, 400, 19), y shape=(1372, 3)
Subject ID 290: X shape=(984, 400, 19), y shape=(984, 3)
Subject ID 291: X shape=(977, 400, 19), y shape=(977, 3)
Subject ID 292: X shape=(1236, 400, 19), y shape=(1236, 3)
Subject ID 293: X shape=(1604, 400, 19), y shape=(1604, 3)
Subject ID 294: X shape=(1517, 400, 19), y shape=(1517, 3)
Subject ID 295: X shape=(1722, 400, 19), y shape=(1722, 3)
Subject ID 296: X shape=(1432, 400, 19), y shape=(1432, 3)
Subject ID 297: X shape=(1461, 400, 19), y shape=(1461, 3)
Subject ID 298: X shape=(1352, 400, 19), y shape=(1352, 3)
Subject ID 299: X shape=(907, 400, 19), y shape=(907, 3)
Subject ID 300: X shape=(1421, 400, 19), y shape=(1421, 3)
Subject ID 301: X shape=(789, 400, 19), y shape=(789, 3)
Subject ID 302: X shape=(1391, 400, 19), y shape=(1391, 3)
Subject ID 303: X shape=(1398, 400, 19), y shape=(1398, 3)
Subject ID 304: X shape=(1474, 400, 19), y shape=(1474, 3)
Subject ID 305: X shape=(1397, 400, 19), y shape=(1397, 3)
Subject ID 306: X shape=(1358, 400, 19), y shape=(1358, 3)
Subject ID 307: X shape=(1496, 400, 19), y shape=(1496, 3)
Subject ID 308: X shape=(865, 400, 19), y shape=(865, 3)
Subject ID 309: X shape=(1530, 400, 19), y shape=(1530, 3)
Subject ID 310: X shape=(1467, 400, 19), y shape=(1467, 3)
Subject ID 311: X shape=(1673, 400, 19), y shape=(1673, 3)
Subject ID 312: X shape=(1425, 400, 19), y shape=(1425, 3)
Subject ID 313: X shape=(1477, 400, 19), y shape=(1477, 3)
Subject ID 314: X shape=(1449, 400, 19), y shape=(1449, 3)
Subject ID 315: X shape=(1302, 400, 19), y shape=(1302, 3)
Subject ID 316: X shape=(1236, 400, 19), y shape=(1236, 3)
Subject ID 317: X shape=(1435, 400, 19), y shape=(1435, 3)
Subject ID 318: X shape=(1478, 400, 19), y shape=(1478, 3)
Subject ID 319: X shape=(1299, 400, 19), y shape=(1299, 3)
Subject ID 320: X shape=(1488, 400, 19), y shape=(1488, 3)
Subject ID 321: X shape=(1447, 400, 19), y shape=(1447, 3)
Subject ID 322: X shape=(620, 400, 19), y shape=(620, 3)
Subject ID 324: X shape=(1363, 400, 19), y shape=(1363, 3)
Subject ID 325: X shape=(1495, 400, 19), y shape=(1495, 3)
Subject ID 326: X shape=(1419, 400, 19), y shape=(1419, 3)
Subject ID 327: X shape=(1624, 400, 19), y shape=(1624, 3)
Subject ID 328: X shape=(1041, 400, 19), y shape=(1041, 3)
Subject ID 329: X shape=(897, 400, 19), y shape=(897, 3)
Subject ID 330: X shape=(1001, 400, 19), y shape=(1001, 3)
Subject ID 331: X shape=(1062, 400, 19), y shape=(1062, 3)
Subject ID 332: X shape=(1443, 400, 19), y shape=(1443, 3)
Subject ID 333: X shape=(1439, 400, 19), y shape=(1439, 3)
Subject ID 334: X shape=(1428, 400, 19), y shape=(1428, 3)
Subject ID 335: X shape=(1163, 400, 19), y shape=(1163, 3)
Subject ID 336: X shape=(1425, 400, 19), y shape=(1425, 3)
Subject ID 337: X shape=(1456, 400, 19), y shape=(1456, 3)
Subject ID 338: X shape=(1379, 400, 19), y shape=(1379, 3)
Subject ID 339: X shape=(1390, 400, 19), y shape=(1390, 3)
Subject ID 340: X shape=(1491, 400, 19), y shape=(1491, 3)
Subject ID 341: X shape=(1393, 400, 19), y shape=(1393, 3)